### ISSUE TITLE
simpletest.py fails

### ISSUE THREAD

**Issue by MatthiasLiszt** [THP-JOE/Python_SI1145#5]
I get the following error when running simpletest.py
`Traceback (most recent call last):
  File "simpletest.py", line 45, in <module>
    sensor = SI1145.SI1145()
  File "build/bdist.linux-armv7l/egg/SI1145/SI1145.py", line 163, in __init__
  File "build/bdist.linux-armv7l/egg/SI1145/SI1145.py", line 170, in _reset
  File "build/bdist.linux-armv7l/egg/Adafruit_GPIO/I2C.py", line 114, in write8
  File "build/bdist.linux-armv7l/egg/Adafruit_PureIO/smbus.py", line 236, in write_byte_data
IOError: [Errno 5] Input/output error
`
Do you have any idea how to fix this

**Comment by pkorivi** [comment]
Did you get some answer?
